// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.media.peerconnection.mtransport_process", true);
user_pref("app.normandy.startupRolloutPrefs.network.process.enabled", true);
user_pref("app.normandy.user_id", "b8144f71-0fa5-471c-8304-1e02cd9771c4");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1647039243);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1647039216);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1647039483);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1647039363);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1647039272);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{f7d5956b-9f20-4d63-9bf5-34653c864796}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1647039213);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 122);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8e1e097e-1917-4914-8f2f-14e0a12b12c4}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1647039214);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1647039231412");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1647041003412");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1647039217494");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1647060817494");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1647039214");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220307142958");
user_pref("browser.startup.homepage_override.mstone", "98.0");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_13\",\"url\":\"https://www.mozilla.org/firefox/welcome/13\",\"expire\":1640908800000}");
user_pref("browser.startup.lastColdStartupCheck", 1647039214);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "offline");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1647039214475");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "98.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.push.userAgentID", "775421f3ca644c939a890c7d3cd1bed9");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220307142958");
user_pref("extensions.lastAppVersion", "98.0");
user_pref("extensions.lastPlatformVersion", "98.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"4cca6d1e-1a5d-4c17-b931-acf3cad4ef6b\",\"formautofill@mozilla.org\":\"3401ae40-c16b-4e1f-ba94-f1214f18d352\",\"pictureinpicture@mozilla.org\":\"1982bf61-e7a4-4268-84a3-4bcdbf0d043a\",\"screenshots@mozilla.org\":\"efbab2e3-d711-4f7f-80ed-6c53c7d676cd\",\"webcompat-reporter@mozilla.org\":\"8c666f0d-983d-4c78-9b86-a7b7ff24dead\",\"webcompat@mozilla.org\":\"6e900184-fe98-42a4-9273-49d2cdb41626\",\"default-theme@mozilla.org\":\"afb7c183-3465-4f6e-bd4c-63c4e7dc7fe6\",\"addons-search-detection@mozilla.com\":\"4a380926-09fc-4293-a4b0-8c314da31e9e\",\"google@search.mozilla.org\":\"0dabc82e-2399-4b73-b1a9-26b47074dd95\",\"amazondotcom@search.mozilla.org\":\"0e88078c-c87e-45b5-94f1-627cf18b0980\",\"wikipedia@search.mozilla.org\":\"c14b76ce-e402-407b-8845-2b52797d97fd\",\"bing@search.mozilla.org\":\"e3789596-9321-486f-913a-61907979f00f\",\"ddg@search.mozilla.org\":\"cb6d2ee7-bd7c-4112-b23a-b61d8e47dbd7\",\"ebay@search.mozilla.org\":\"daa0c01b-ef29-4239-bf30-79586d1e9ca8\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1647039214);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "d4c68a5a-e4ae-425b-8b1a-1a89c18e16a7");
user_pref("toolkit.startup.last_success", 1647039212);
user_pref("toolkit.telemetry.cachedClientID", "d13afb74-ff4d-45ac-92c0-29ac35a15645");
user_pref("toolkit.telemetry.previousBuildID", "20220307142958");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
