// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.media.peerconnection.mtransport_process", true);
user_pref("app.normandy.startupRolloutPrefs.network.process.enabled", true);
user_pref("app.normandy.user_id", "960434b8-45b2-46a5-936b-9809d1d84092");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1647316308);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1647316307);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{c82b600c-0778-481c-9e86-61fa78ca74d9}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1647316305);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 122);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2bf20a88-6344-4a70-912b-c6e01e9cae33}");
user_pref("browser.newtabpage.pinned", "[]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1647316306);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1647316310219");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1647337910219");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1647316306");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220314212635");
user_pref("browser.startup.homepage_override.mstone", "98.0.1");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_13\",\"url\":\"https://www.mozilla.org/firefox/welcome/13\",\"expire\":1640908800000}");
user_pref("browser.startup.lastColdStartupCheck", 1647316306);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "offline");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1647316306674");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "98.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.push.userAgentID", "fae3b54449c547e1b8a00a3d09952f2e");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220314212635");
user_pref("extensions.lastAppVersion", "98.0.1");
user_pref("extensions.lastPlatformVersion", "98.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"27c83e19-579b-4d30-8b53-572039252e32\",\"formautofill@mozilla.org\":\"1488fbae-d0f2-4a9a-96b2-3b1557d630a7\",\"pictureinpicture@mozilla.org\":\"6c42af73-ebf3-4214-97b4-1c1adbe6c065\",\"screenshots@mozilla.org\":\"b0dcdeee-25a9-49c5-8387-e38de232db59\",\"webcompat-reporter@mozilla.org\":\"46d4d3ca-f41b-41a0-8b9b-9b63c1273148\",\"webcompat@mozilla.org\":\"09271989-ddb7-4c98-ac2a-00d485bf731d\",\"default-theme@mozilla.org\":\"d8e45011-48a5-46fe-980d-292d18c93ae2\",\"addons-search-detection@mozilla.com\":\"91463142-e952-4975-8c68-141356532ec2\",\"google@search.mozilla.org\":\"b386f7fb-7a73-4449-9932-406c3a286cfd\",\"amazondotcom@search.mozilla.org\":\"9b78ee5e-5205-49a6-849a-75b7dcb95bd1\",\"wikipedia@search.mozilla.org\":\"28369411-5b79-4867-bbb1-77ee78baf93d\",\"bing@search.mozilla.org\":\"b665439c-80d7-4ad6-8fcd-7e2c5cbc2f2b\",\"ddg@search.mozilla.org\":\"ff82ab91-bc9d-493e-b737-a01496f2b80a\",\"ebay@search.mozilla.org\":\"70e4875c-b7d6-4857-a7a2-606dd144fb30\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1647316306);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "44cbd12f-f06c-4089-8820-bfa02e333df1");
user_pref("toolkit.startup.last_success", 1647316304);
user_pref("toolkit.telemetry.cachedClientID", "fb770910-8f76-4d8a-8a21-abefc98c9a71");
user_pref("toolkit.telemetry.previousBuildID", "20220314212635");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
